import { theme, type ThemeConfig } from 'antd';

export const portalPalette = {
  primary: '#0F766E',
  primaryHover: '#14988C',
  text: '#1C2B2A',
  textSecondary: '#5C6F6C',
  menuItem: '#3D524F',
  bgLayout: '#F3F7F5',
  siderBg: '#F7FBFA',
  selectedBg: '#D5F0EA',
  hoverBg: '#E7F3F0',
  tableHeaderBg: '#E7F3F0',
  rowHoverBg: '#F3FAF8',
  border: '#DCE7E3',
  borderSoft: '#E3EBE8',
  twoToneSecondary: '#D5F0EA',
  loadHigh: '#E8A317',
  heroText: '#1C2B2A',
  heroTextMuted: 'rgba(28, 43, 42, 0.72)',
  heroWashStart: 'rgba(247, 251, 250, 0.92)',
  heroWashEnd: 'rgba(213, 240, 234, 0.78)',
} as const;

export const portalTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary: portalPalette.primary,
    colorInfo: '#3B82C4',
    colorSuccess: '#2F9E6B',
    colorWarning: '#D97706',
    colorError: '#C24141',
    colorLink: portalPalette.primary,
    colorBgLayout: portalPalette.bgLayout,
    colorBgContainer: '#FFFFFF',
    colorText: portalPalette.text,
    colorTextSecondary: portalPalette.textSecondary,
    colorBorder: portalPalette.border,
    colorBorderSecondary: '#E7EFEC',
    borderRadius: 12,
    fontFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    boxShadow: '0 1px 2px rgba(28, 43, 42, 0.04), 0 6px 16px rgba(28, 43, 42, 0.04)',
    boxShadowSecondary: '0 1px 2px rgba(28, 43, 42, 0.04)',
    boxShadowTertiary: '0 1px 2px rgba(28, 43, 42, 0.03), 0 4px 12px rgba(28, 43, 42, 0.04)',
  },
  components: {
    Layout: {
      siderBg: portalPalette.siderBg,
      lightSiderBg: portalPalette.siderBg,
      headerBg: '#FFFFFF',
      bodyBg: portalPalette.bgLayout,
      footerBg: portalPalette.bgLayout,
      triggerBg: portalPalette.hoverBg,
      lightTriggerBg: portalPalette.hoverBg,
    },
    Menu: {
      itemBg: 'transparent',
      itemColor: portalPalette.menuItem,
      itemHoverBg: portalPalette.hoverBg,
      itemHoverColor: portalPalette.primary,
      itemSelectedBg: portalPalette.selectedBg,
      itemSelectedColor: portalPalette.primary,
      itemBorderRadius: 10,
      itemMarginInline: 8,
      iconSize: 16,
    },
    Table: {
      headerBg: portalPalette.tableHeaderBg,
      headerColor: portalPalette.text,
      rowHoverBg: portalPalette.rowHoverBg,
      borderColor: portalPalette.borderSoft,
      headerSplitColor: 'transparent',
    },
    Progress: {
      defaultColor: portalPalette.primary,
      remainingColor: portalPalette.hoverBg,
    },
    Button: {
      primaryShadow: '0 2px 0 rgba(15, 118, 110, 0.06)',
    },
  },
};
