services:
  postgres:
    image: postgres:16
    container_name: racing_manager_db
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Europe/Moscow
      PGTZ: Europe/Moscow

    command: ["postgres", "-c", "timezone=Europe/Moscow"]

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      # Том для хранения данных
      - postgres_data:/var/lib/postgresql/data
      # SQL для инициализации при первом запуске
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: